workflows:
  ios-release:
    name: pdf_D
    environment:
      groups:
        - ios_code_signing  # 包含证书的环境变量组
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.pdf_zq"  # 替换为你的实际 Bundle ID
      xcode: latest  # 使用最新 Xcode 版本
      cocoapods: default  # 使用默认 CocoaPods 版本
      flutter: stable
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'develop'
          include: true
    
    scripts:
      # 步骤1: 安装和配置 CocoaPods
      - name: Install and configure CocoaPods
        script: |
          # 确保 CocoaPods 正确安装
          gem install cocoapods --user-install
          pod --version
          
          # 设置 Pod 仓库
          cd ios
          pod repo update
      
      # 步骤2: 获取 Flutter 依赖
      - name: Get Flutter dependencies
        script: |
          flutter pub get
          flutter clean
      
      # 步骤3: 安装 iOS 依赖
      - name: Install iOS dependencies
        script: |
          cd ios
          # 清除 Pods 缓存
          rm -rf Pods Podfile.lock
          # 重新安装 Pods
          pod install --repo-update
          cd ..
      
      # 步骤4: 初始化钥匙串（代码签名）
      - name: Set up keychain
        script: |
          keychain initialize
      
      # 步骤5: 构建 IPA
      - name: Build iOS app
        script: |
          # 使用 Flutter 直接构建 IPA
          flutter build ipa --release \
            --export-options-plist=ios/ExportOptions.plist
          
          # 或者使用 xcodebuild
          # xcode-project build-ipa \
          #   --project "$CM_BUILD_DIR/ios/Runner.xcodeproj" \
          #   --scheme "Runner" \
          #   --output "$CM_BUILD_DIR/build/ios/ipa"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $CM_BUILD_DIR/flutter_drive.log
    
    publishing:
      email:
        recipients:
          - your-email@example.com
      slack:
        channel: '#builds'
        notify_on_build_start: true
